.to_i
.to_s
.zero?
.sum
.map
.abs
.next
.dup
.times{
.ceil
.bit_length
Integer.sqrt(n)
.upto
.downto
.round
.floor
.chr
.default
Hash.new
.new
Set[]
[0,*a,0]
.delete
.push
.pop
.include?(
.all?
.any?
.empty?
.combination(3)
.combination(2)
.permutation
.each_slice
.each_cons
.take(n)
.take_while{
.slice_after
.slice_before
.size
.flatten
.keys
.values
.merge
.dig
.filter
.each_with_index
.invert
.has_key?
.has_value?
key
.index
.start_with?
.to_a
.chars
.digits
.gsub(
.strip
.split
.map
.sum
.reverse
.sort
.reverse
.sort
.count
.downcase
.upcase
.chars
.rindex
.include?
.index
.map
.sum
.sort
.count
.fill
.fill(b..){'0'}
.bsearch
.any?{
.all?{
.any?(&:even?)
.new
.each
.drop
.last
.first
.flat_map
.rotate
.zip
.zip
.transpose
.transpose
.product
.union
.min
.max
.max_by
.min_by
.min
.max
.max_by
.min_by
.shuffle
Enumerator.produce
.lazy
def
if
while
until
unless
end
end
else
p
ans
for
return
return
if
while
.each{
.each_with_index{
.with_index{
.with_index{
.to_set
.even?
[a]
by
&&
input[/^[a-z]*$/]
/^[0-9]$/
.to_i
'invalid'
.tally
.tally
.bsearch_index
.map.with_index
.rect
Complex
rescue
nums
target
.succ
.pred
break
.gcd
.lcm
.each_index
.join
and
and
or
not
num
str
string
.unshift(
.shift
.reduce(&:word)
.reduce{|x,y|
.then{
.then{
.then{
.map
loop{
.delete_prefix('word')
.delete_suffix('word')
.swapcase
raise
StopIteration
.ceildiv(3)
.ceildiv(6)
.ceildiv(2)
.ceildiv(b-c)
true
false
words
names
.clamp(
.clamp(0..)
.repeated_permutation(
.then{
.then{_1.size>0 ? _1 : [0]}
.slice_when
.chunk
_by{
_by.with_index
filter{_1>0}
.group_by{
.partition{
&:even?
&:to_i
[0]
[_1..]
[.._1]
[..._1]
[_1.._2]
[
]
{
}
[1]
[2]
[r,c]
row
column
(?0..?9)
(?a..?z)
(?A..?Z)
[*?0..?9,*?a..?z]
.each_slice(x)
%w[0 0 0 1 1 2 2 0 2 1].map(&:to_i).each_slice(2).to_a
.clamp(..b)
.compact
&&
||
!
!
!
&&
||
'no result'
"#{word}"
.count{_1>_2}>=0
"value is #{word}"
value
.map{_1.to_i}
.map(&:to_i)
.sort
.sum
.each_cons(2)
.each_slice(2)
.slice_before{_1.odd?}
('a'..'z').to_a.each_cons(2).each{p 4 if _1!=_2}
(2..Integer.sqrt(n)).all?{n%_1!=0}
s.chars.tally.max_by{_2}[0]
h=Hash.new{_1[_2]=[]}
(n.to_s+n.next.to_s).to_i.then{_1==Integer.sqrt(_1)**2}
num*2==(1..Integer.sqrt(num)).filter{num%_1==0}.map{_1**2==num ?_1:_1+num/_1}.sum
num==(1...num).filter{num%_1==0}.sum
(2..).lazy.filter{|p| (2..Integer.sqrt(p)).all?{p%_1!=0}}.take(n).to_a[0]
.combination(2)
q.flat_map{[_1,_2+b,_1+_2+2*b,_1-_2-b]}.tally.then{_1.values.sum-_1.size}
(1..n).map{n.to_s*_1}.map(&:to_i).sum.to_s
(1..).lazy.filter{|x|[x.to_s,x.to_s(2)].all?{_1==_1.reverse}}.take(n).to_a.last
p.combination(2).to_set.count{(_1-_2).abs==k}
ss.permutation.any?{_1*''==s}
s.times{a=[0,*a,0];a=a.each_cons(2).map{_1+_2}}
.flat_map{[[_1,_1*2]]}
.lazy
.to_a
.to_s
.to_s(2)
.slice_after(1)
.permutation
.any?
.all?
.none?
.empty?
.size
Enumerator.produce(
*''
(h=a.tally).default=0
s.split.filter{_1.size.even?}.map(&:reverse)*' '
with_index
.abs
.to_i
next
.dup
.times
Integer.sqrt
Hash.new{_1[_2]=[]}
.flat_map{[_1,_2]}
.filter{_1.size.even?}
.sort_by.with_index{_1}
s.chars
bsearch_index{_1>=5}
q<<a while a=s.index('in')
code.gsub('-','').chars.map(&:to_i).zip(10.downto(1)).map{|x, y|x*y }.sum%11==0
end
(_1-_2).abs
.split
.index('yes')
.rindex('no')
.last(3)
.lazy
.to_set
.with_index
.all?{_1%12==1}
.any?{_1==_2}
.to_i
str2.chars.each{i+=1 if str1[i]==_1}
i==str1.size
arr.sort.last(2).sum
q=->x{[x[0].to_i-1,x[1].ord-97]}
a+=a.map{_1.reverse}
Set[]
!1
!!1
a.tally
(x=a.tally).default=0
s,v[x],v[y]=s+(y-x)*v[x],0,v[x]+v[y] if x!=y
.minmax
v.permutation(2).map{(_1-_2)}.max
def
'Yes'
'string'
nums.index(target)||-1
n+=1 until n.digits.all?{[3,5].include?(_1)}
_by
.sum
.min
.max
_by
.map
.filter
(1..n).map{(n.to_s*_1).to_i}.sum.to_s
.map(&:chr)*''
arr.chars.map(&:to_i).reverse.map.with_index{|x, y| y.odd? ? (x*2).digits.sum : x}.sum%10==0
b.combination(2).count{(_1-_2).abs==differ}
s.chars.each_index.flat_map{|i| (i+1..s.size).map{s[i..._1]}}.filter{_1==_1.reverse}.max_by{_1.size}
s.times{ans=[0,*ans,0].each_cons(2).map{_1+_2}}
.succ
.pred
n.gcd(m)
r1=(r1-r2).abs
c1=(c1-c2).abs
[r1,n-r1].min+[c1,m-c1].min
break
.join
*''
*' '
numbers.filter.with_index{_1.even? and _2.even?}.then{_1.size>0 ? _1 :[0]}
.then
.then
.reduce
.reduce(&:gcd)
.reduce(:^)
first.zip(second).map{|x, y| x-y}
(1...s.size).count{s[..._1].to_i<=s[_1..].to_i and s[_1]!='0'}
.repeated_permutation(n)
.map(&:to_i)
(1..num).map{num.to_s*_1}.sum(&:to_i).to_s
.flatten
.sum{_1*_2}
.reduce(0,&->x,y{x*26+y})
?(
):(
)
.minmax.then{_2-_1}
.filter
.chars
.to_set
.sum(&:to_i)
.sum{_2.size}
.downcase.delete('^a-z')
.max(k)[-1]
.minmax.then{_2-_1}
.with_index
.with_index
.size
a=%w[9:00 10:00 11:30 12:30].each_slice(2).to_a
dop=['12:00','13:00']
f=->t{
t.split(":").zip([60,1]).sum{_1.to_i*_2}
}
g=->t{
'%02i:%02i'%[t/60,t%60]
}
p g[f[a[0][1]]]
tm=0
ans=[]
was=!1
a.each{|x,y| 
if f[y]>f[dop[0]] and not was
xx,yy=f[dop[0]],f[dop[1]]
l=yy-xx
xx=[tm,xx].max
yy=xx+l
tm=yy
ans<<[g[xx],g[yy]]
was=1
end
x,y=f[x],f[y]
l=y-x
x=[tm,x].max
y=x+l
tm=y
ans<<[g[x],g[y]]
}
p ans
p (0...1<<tasks.size).map{|x|
x if tasks.filter.with_index{x[_2]==1}.combination(2).all?{_1.split.to_set.intersect?(_2.split.to_set)}
}.compact
.then{|x| x.filter{|y| x.all?{y==_1||(y&_1!=y)}}}
.map{|x| tasks.filter.with_index{x[_2]==1}}
ss.permutation.any?{_1.join==s}
ss.permutation.any?{_1.join==s}
idx=%w[0 0 0 1 0 2 1 0 1 1 1 2 2 0 2 1 2 2 3 1].map(&:to_i).each_slice(2).to_a
code.each_cons(2).map{|x,y| idx[x.to_i].zip(idx[y.to_i]).map{(_1-_2).abs}+1}.sum
q=[]
a1.size.times{
q<<[a1.shift,a2.shift,a3.shift]
(a1,a2=a2,a1) if _1.even?
(a3,a2=a2,a3) if _1.odd?
}
g,e,a=2,1,1
until e==0
e-=1
(a+=1;next) if a<g
g+=1
end
p a
x=[g-a,e].min
e-=x
a+=x
a+e/2
r=(r1-r2).abs
c=(c1-c2).abs
[r,r-n].min+[c,m-c].min
a,b=a.partition.with_index{_2.even?}
[a.sum-b.sum,a.sum-b.sum-2*a.min+2*b.max].max
q=0
s=s.gsub('**'){q+=1;'@'}
a=s.count('*')
return [q,a+s.chars.each_cons(2).count{(?0..?9).include?(_1) and (?a..?z).include(_2)}]
%w[0 0 1 1 0 2 2 0 1 2 2 1 2 2].map(&:to_i).each_slice(2).to_a.each{|x,y| q=[a[x],b[y]].min;a[x]-=q;b[y]-=q;ans+=q}
skill.sort[1..].sum>=k
s.chars.tally.values.then{_1.sum-_1.max}
a.ceildiv(c-b)
purchses.filter{_2.start_with?(month)}.tally.max_by{_2}[0]
words.map{|x| 100.times{x=x.gsub(/'./,'').gsub(/.'/,'')};x}.join
((first+[first[0]]).each_cons(2).to_a.map(&:sort).to_set&
(second+[second[0]]).each_cons(2).to_a.map(&:sort).to_set).first
b=10**100
queens.flat_map{|x,y| [x+b,y,x+y+2*b,x-y+3*b]}.tally.then{_1.values.sum-_1.size}
x='9'*(a/9)+(a%9).to_s
x+='0'*(b-x.size)
skill.sort.reverse[0...(skill.size.ceildiv 2)].then{_1.size*3-_1.sum}
.partition
